### ISSUE TITLE
About only tumor cell (cluster)

### ISSUE THREAD

**Issue by soralsr** [AntonioDeFalco/SCEVAN#112]
Hi @AntonioDeFalco, thanks for this amazing package.

I met problems, when I used SCEVAN to identify heterogeneity in tumor cluster ( only tumor cell ).
> **PipelineCNA** results detected the normal cells in tumor cell cluster, when I applied it. (I used only tumor cell)

> Can't I just detect the tumor cell (not contain normal cell) using SCEVAN?

Expecting your reply.
Thank you

**Comment by AntonioDeFalco** [comment]
Hi @soralsr,
For the inference of the copy number from scRNA data SCEVAN, like other methods, requires the use of a reference of normal cells to infer the copy number, which is why SCEVAN assumes that in the matrix of a tumour sample there is the presence of some tumour microenviroment cells to be used as a reference. Therefore, I do **not advise** using only tumour cells for heterogeneity analysis; it is possible to use the synthetic reference generated from the data with SCEVAN, but I recommend adding normal cells to the matrix to obtain a **more reliable** copy number analysis. 

Thanks. Regards
