### ISSUE TITLE
Results from a Normal sample gives all tumor predictions

### ISSUE THREAD

**Issue by Prakrithi-P** [AntonioDeFalco/SCEVAN#118]
Hi,
   Thanks for the great tool. It works great for single sample pipeline with a tumor sample, correctly identifying tumor cells. However, as a control, when I test for sample that are normal (no tumor) - the results give
- All tumor predictions for some normal samples (i would expect all normal predictions)
- or some tumor predictions for other smaples

It would be great if you could help me understand this behaviour

Thanks,
Prakrithi

**Comment by AntonioDeFalco** [comment]
Hi @Prakrithi-P,
SCEVAN was designed for analysing scRNA data with malignant cells, which is why it **assumes** the presence of cancer cells in the sample. This can lead to errors when analysing matrices of only normal cells. A tumor fraction greater than 0% is **assumed** in the pipeline,  you can test matrices with different percentages of tumor fraction but not healthy samples.

Thanks.
