### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by StevenTur** [AntonioDeFalco/SCEVAN#17]
Hello,

I would like to share with you a problem I have encountered. I managed to make SCEVAN work well on the test data you provided. Once successful I tried with my own data and it gave me this error during the annotations gene coordinates step.

Here is the error :

[1] "3) Annotations gene coordinates"

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: doParallel
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
**Error in `colnames<-`(`*tmp*`, value = colnames(geData)) : 
  attempt to set 'colnames' on an object with less than two dimensions
Timing stopped at: 38.39 10.32 15.27**

> 

I am working on mouse data. But I don't think that's where the problem comes from. Do I have to convert my data into a certain form for SCEVAN to work?

Sincerely,

Steven

**Comment by AntonioDeFalco** [comment]
Sorry but at the moment SCEVAN only works with human samples. Suppose we add mouse in future updates. Thanks for your interest, regards.

**Comment by StevenTur** [comment]
Hi, thank you for your answer.

Do you think I can adapt it myself for mouse? Is it complicated to modify the code to be able to analyze the data coming from mouse?

**Comment by AntonioDeFalco** [comment]
In the last commit ([d653896](https://github.com/AntonioDeFalco/SCEVAN/commit/d65389647da3a06afd25dabf05e333d338398b4b)) I added the possibility of analysing mouse samples. At the moment, it is not yet possible to use the subclonal analysis, due to some changes to the code which I will be carrying out shortly.

You can currently use the pipeline in this way:
pipelineCNA(mtx_counts, SUBCLONES = TRUE, organism = "mouse")

Since the identification of confidant normal cells has not yet been verified by us for this organism, you can use a list of personal signatures (geneSet) of normal cell types:
pipelineCNA(mtx_counts, SUBCLONES = TRUE, AdditionalGeneSets = geneSet, SCEVANsignatures = FALSE, organism = "mouse")

Regards.

**Comment by StevenTur** [comment]
Thank you for your reply.

I do have confident normal WT cells that i know are not aneuploids. I tried to use this in the (AdditionalgeneSet) but it's not working. However, it was able to generate the heatmaps when i combined WT and cancer cells in the (mtx_counts) but not the rest of the output (eg : Volcano, tree, etc .. ).

Thank you very much for your help!

**Comment by AntonioDeFalco** [comment]
If you know normal cells that are in the matrix you want to analyse, you can pass them to SCEVAN as a **_norm_cell_** parameter not AdditionalgeneSet. **_AdditionalgeneSet_** expects you to pass **_Gene Sets_** representing normal cell types useful for classifying normal cells within the matrix.

It is not able to generate Vulcan, tree, etc.. because they are part of the subclone analysis which as I told you cannot yet be used for mouse samples. But in a future update it will be possible.

Thank you for your interest and sorry for the delay.

**Comment by zhangpebbels** [comment]
Hello,
Recently,I encountered some problems when i run "compareClonalStructure".
Error in gzfile(file, "wb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file './output/sample1_confidentNormal_MWW.RData', probable reason 'No such file or directory'
Timing stopped at: 293.1 10.78 320.3
 I don't know whether "compareClonalStructure" is one step , or i need to run spilt before.
Sincerely

**Comment by AntonioDeFalco** [comment]
> Thank you for your reply.
> 
> I do have confident normal WT cells that i know are not aneuploids. I tried to use this in the (AdditionalgeneSet) but it's not working. However, it was able to generate the heatmaps when i combined WT and cancer cells in the (mtx_counts) but not the rest of the output (eg : Volcano, tree, etc .. ).
> 
> Thank you very much for your help!

Hi @StevenTur, 
I just wanted to let you know that in the recent package updates, we fixed the subclone analysis pipeline for mouse samples as well. You should now be able to get all output files. 

Please let me know if everything is all right. Thanks Regards.
