### ISSUE TITLE
Clone tree failed due to dplyr version

### ISSUE THREAD

**Issue by River366** [AntonioDeFalco/SCEVAN#35]
Dear author,
After running _pipelineCNA_ finish, there is a notice say the plotTree function need dplyr version 1.0.5. So, it's failed to plot the tree. 
Would you mind fix the tiny problem in future?

Thanks for your help!

**Comment by AntonioDeFalco** [comment]
Hi @River366,
Yes unfortunately the problem depends on the ggtree library used to graph the phylogenetic tree which necessarily wants version 1.05 of dplyr as explained here https://github.com/AntonioDeFalco/SCEVAN/issues/27#issuecomment-1245378194. Certainly I will try in a next update to not depend on ggtree in order to solve the problem. 

Thanks for your interest. Regards.

**Comment by River366** [comment]
Sorry for my trouble. Thanks a lot!
