### ISSUE TITLE
Heatmap generation error

### ISSUE THREAD

**Issue by luglilab** [AntonioDeFalco/SCEVAN#48]
Hi,

I'm have tested your code with 10 samples and i got the following error:
 

"Error in plot.new(): figure margins too large
Traceback:

1. SCEVAN::multiSampleComparisonClonalCN(listCountMtx_1, analysisName = "GSE131907_1", 
 .     organism = "human", par_cores = 20)
2. plotAllClonalCN(names(listCountMtx), name = analysisName)
3. plotSegmentation(CNV)
4. with(data = CNV, expr = {
 .     plot(x = Pos, y = Mean, pch = NA_integer_, ylab = "Copy number", 
 .         xlab = "CHR", xaxt = "n", type = "l", xgap.axis = ref)
 .     polygon(x = c(min(Pos), Pos, max(Pos)), y = c(ref, Mean, 
 .         ref), col = "red")
 .     clip(x1 = min(Pos), x2 = max(Pos), y1 = min(Mean), y2 = ref)
 .     polygon(x = c(min(Pos), Pos, max(Pos)), y = c(ref, Mean, 
 .         ref), col = "blue")
 . })
5. with.default(data = CNV, expr = {
 .     plot(x = Pos, y = Mean, pch = NA_integer_, ylab = "Copy number", 
 .         xlab = "CHR", xaxt = "n", type = "l", xgap.axis = ref)
 .     polygon(x = c(min(Pos), Pos, max(Pos)), y = c(ref, Mean, 
 .         ref), col = "red")
 .     clip(x1 = min(Pos), x2 = max(Pos), y1 = min(Mean), y2 = ref)
 .     polygon(x = c(min(Pos), Pos, max(Pos)), y = c(ref, Mean, 
 .         ref), col = "blue")
 . })
6. eval(substitute(expr), data, enclos = parent.frame())
7. eval(substitute(expr), data, enclos = parent.frame())
8. plot(x = Pos, y = Mean, pch = NA_integer_, ylab = "Copy number", 
 .     xlab = "CHR", xaxt = "n", type = "l", xgap.axis = ref)
9. plot.default(x = Pos, y = Mean, pch = NA_integer_, ylab = "Copy number", 
 .     xlab = "CHR", xaxt = "n", type = "l", xgap.axis = ref)
10. plot.new()"

**Comment by AntonioDeFalco** [comment]
Hi @luglilab,
I fixed in the last commit [51819bd](https://github.com/AntonioDeFalco/SCEVAN/commit/51819bd632bc57e6a039ca208d4880de61d05efc) the problem.  You can reinstall  SCEVAN and re-run the analysis function **_multiSampleComparisonClonalCN_** or just run the **_plotAllClonalCN_** function (having as working directory the same one where you previously performed the analysis)  with the sample names to be plotted without having to re-run the analysis:

  `plotAllClonalCN(names(listCountMtx_1), name = "GSE131907_1")`

Regards.
