### ISSUE TITLE
Clone Tree

### ISSUE THREAD

**Issue by orange-3711** [AntonioDeFalco/SCEVAN#54]
Hi @AntonioDeFalco 

SCEVAN is very convenient and quick. But there is no clone tree plot for each sample during multisample analysis. Can this function be added later? Maybe I didn't find the right way to use it.

And I have another question. There is no rowname in the CNAmtx.RData. Does each row correspond to the row of the input count_mtx?

**Comment by AntonioDeFalco** [comment]
Hi @orange-3711 ,

> But there is no clone tree plot for each sample during multisample analysis.

Regarding the multi-sample analysis, the analysis currently performs a comparison of the CLONAL profile between several samples, so it does not analyze the subclonal structure of each sample, which is why you do not get the clone tree of each sample (you have to use pipelineCNA for each sample to get this type of analysis). 

> Can this function be added later?

I added this function in the last commit, so if you reinstall SCEVAN and use the multi-sample analysis on more than two samples you will now get a clone tree about the CLONAL profile of the different samples.

> And I have another question. There is no rowname in the CNAmtx.RData. Does each row correspond to the row of the input count_mtx?

You can find the row annotations in the SAMPLE_NAME_count_mtx_annot.RData file.

I hope it is clear. Regards

**Comment by orange-3711** [comment]
> I added this function in the last commit, so if you reinstall SCEVAN and use the multi-sample analysis on more than two samples you will now get a clone tree about the CLONAL profile of the different samples.

This is a very useful function for inferring tumor evolution. Thanks!!
