### ISSUE TITLE
About 'norm_cell'

### ISSUE THREAD

**Issue by xxbb23** [AntonioDeFalco/SCEVAN#62]
Hi Antonio,
    When I used SCEVAN to deal with my own Single-cell data,which contains two parts, tumor samples and normal samples.I met a problem.I don't know the meaning of the parameter ‘norm_cell’? Do I need to set it, will it affect the results of the analysis?
    I have two ideas. The first is to set the T cells and B cells in the normal samples to "norm_cell"; the second is that no "norm_cell" is set to see the CNA of the Epithelial Cells.
    expecting your reply
    thanks very much~

**Comment by AntonioDeFalco** [comment]
> I don't know the meaning of the parameter ‘norm_cell’? Do I need to set it, will it affect the results of the analysis?

The _**norm_cell**_ parameter can be used to pass a vector containing cell names that are already known to be normal cells to SCEVAN to simplify or achieve better analysis with SCEVAN (since they will be used as a normal reference for the analysis). Instead, it should be set to NULL if no normal cells are known to be present in the scRNA matrix and you want to obtain the tumour/normal classification automatically from SCEVAN.

> When I used SCEVAN to deal with my own Single-cell data,which contains two parts, tumor samples and normal samples

With SCEVAN you can analyze your tumour samples which generally contain a part of normal cells and a part of tumour cells depending on tumour purity. As far as your normal samples are concerned, if you expect there to be no tumour cells in the sample, do not analyze these samples with SCEVAN, which is designed and implemented to only analyse tumour samples.

I hope it is clear.
