### ISSUE TITLE
About dplyr-1.0.5

### ISSUE THREAD

**Issue by DrLeeven** [AntonioDeFalco/SCEVAN#63]
I don't know why I have to use dplyr-1.0.5 when drawing the "tree". But seurat only needs dplyr-1.0.10 or above to be able to library. can this bug be fixed?

**Comment by AntonioDeFalco** [comment]
The problem unfortunately depends on ggtree library which I use to make the Phylogenetic tree graph that necessarily wants version 1.05 of dplyr otherwise it gives this error (https://github.com/YuLab-SMU/ggtree/issues/399).

I will replace the library for the phylogenetic tree in a future update.

Thanks. Regards
