### ISSUE TITLE
Step 8 error: Error in serialize(data node$con) error writing to connection

### ISSUE THREAD

**Issue by LucienYe** [AntonioDeFalco/SCEVAN#71]
Dear SCEVAN developers,

I tried to perform SCEVAN on a large dataset (containing ~160,000 cells), but I encountered this error below. I'm running on a windows virtual machine with 122GB RAM and 16 CPUs. How could I solve this problem? Higher memory or reduce parallel cores?
I would appreciate it very much if you could offer me some suggestions. Thank you!

![image](https://github.com/AntonioDeFalco/SCEVAN/assets/137428681/d6cca4d4-b312-4429-bfaf-c7fe95b3ec4d)

**Comment by AntonioDeFalco** [comment]
Hi @LucienYe,
We have never analysed samples with such a large number of cells. I believe you have aggregated several samples into one matrix, but because of the way SCEVAN is designed and the way the copy number is inferred from the reference of the normal cells within the sample, regardless of the memory allocation error, it is recommended to analyse the samples individually with SCEVAN with regard to the **_pipelineCNA_** function and to use the **_multiSampleComparisonClonalCN_** function instead if you want to compare several samples passed as a list.

Regards. Let me know if this solves the problem and you can still perform the desired downstream analysis.
